### ISSUE TITLE
How to fix this problem?

### ISSUE THREAD

**Issue by Liskelleo** [matthewwardrop/python-parameters#3]
Hi, there. Recently I've installed your package and start to use. When I first downloaded it, I could import your third-party library to work normally, but when I opened the computer the next day and wanted to import your third-party library, the following problem appeared----

> from parampy import SlQuantity,Parameter
```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from parampy import SlQuantity,Parameter
  File "C:\Users\***\***\***\***\Python\Python39\lib\site-packages\parampy\__init__.py", line 12, in <module>
    from .parameters import Parameters, Bounds
  File "parampy\parameters.pyx", line 6, in init parampy.parameters
  File "C:\Users\***\***\***\***\Python\Python39\lib\site-packages\parampy\iteration.py", line 3, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

> from parampy import SlQuantity,Parameter
```
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    from parampy import SlQuantity,Parameter
  File "C:\Users\***\***\***\***\Python\Python39\lib\site-packages\parampy\__init__.py", line 12, in <module>
    from .parameters import Parameters, Bounds
  File "parampy\parameters.pyx", line 3, in init parampy.parameters
ImportError: cannot import name errors
```

**Comment by Liskelleo** [comment]
The simplest way to solve this problem is to remove all the content related to this `resource` library in src. However, I don't know much about details behind this error. So if you accidentally go through this issue and have better understandings, don't hesitate to let me know at once.
Btw, my python version is 3.9.6.
